language: java
sudo: false
install: true

addons:
  sonarcloud:
    token:
      secure: "zRCoq2z2rLzwaS7KG3DOh1Og9ZK8lC6Q+YHLDTHUVE8J5U4C0lDSS7/z9QjXPxHEHPHk9q8IK9FdnIQ1x3pbOP9GT/WUfDfufxxWC5czviKh2Zq0jxkTqruqSuI9mTRjAo7EJvfdxAgupUtsXOGFi+76UV46fw+kK/nvNRQe8nI8SjanXatEmK0DKil1T3k9mgotjELY4qbYpkJqvXOPoGxczrb3AKTTalDusshPGGa2PyWPgi0+ugQwYqNqhN/4xbS38dov/lgisRDyHtCKta98GIW88QO8oGxDIpQKUClX4zRzdGFuNEwnZ6T49noy4M2meeummMkzdCNgv5EFJ1wveMAWUbYlyZQDNcxeqq8Rr8W2F6UnT5MFLvJjegDCitYX4bdqVAFcOCV14soLfT4Lv2oV40yZ1fVX/8ycY5SzRchUwzgKxpNAsCrnLw52F1hlkQyUniwdPt/oqY036jDONvae50njI7olzpblFq4fmz9Xv8FZdExE+H72llsDQ2A0MNiTC3KIuzlNYIIWMi9YU1n3vzDCpT/1Ch793gMW63chit4iR8NSH+7llx5rMl3nBwiIRazmw5slcsL1Lg1t+uYv+lIduABMh0f5LlWHPlKHL1jUy/9VnLN3iZsxKWjgFs0VhS57vcqI8f8sCGyDPqoGiy5QAaiC0Iabse4="

jdk:
- oraclejdk8

notifications:
  email:
    recipients:
    - akamen@blackducksoftware.com
    - ekerwin@blackducksoftware.com
    - rotte@blackducksoftware.com

script:
 - "./gradlew clean build sonarqube"

after_success:
 - "./gradlew test jacocoTestReport coveralls"
 - export DETECT_GRADLE_EXCLUDED_CONFIGURATIONS=compileOnly,compileClasspath
 - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
  - "$HOME/.gradle"
  - ".gradle"
